FROM node:23-alpine3.20

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
RUN ls -a
RUN apk add --no-cache git
WORKDIR /app
COPY . .
RUN npm install 
RUN npm install -g nodemon

EXPOSE 4000

CMD [ "npm", "run", "dev" ]